const UmaDatas = [
  {name: '新衣装トウカイテイオー', img: '/img/teio.png'},
  {name: 'トウカイテイオー', img: '/img/teio2.png'},
  {name: '新衣装メジロマックイーン', img: '/img/mac.png'},
  {name: 'メジロマックイーン', img: '/img/mac2.png'},
  {name: 'ビワハヤヒデ', img: '/img/hayahide.png'},
  {name: 'ミホノブルボン', img: '/img/burubon.png'},
  {name: 'テイエムオペラオー', img: '/img/operao.png'},
  {name: 'スペシャルウィーク', img: '/img/supe.png'},
  {name: 'サイレンススズカ', img: '/img/suzuka.png'},
  {name: 'マルゼンスキー', img: '/img/maruzen.png'},
  {name: 'オグリキャップ', img: '/img/oguri.png'},
  {name: 'タイキシャトル', img: '/img/taiki.png'},
  {name: 'シンボリルドルフ', img: '/img/koutei.png'},
  {name: 'ライスシャワー', img: '/img/rice.png'},
  {name: 'ゴールドシップ', img: '/img/gorusi.png'},
  {name: 'ウオッカ', img: '/img/wokka.png'},
  {name: 'ダイワスカーレット', img: '/img/suka.png'},
  {name: 'グラスワンダー', img: '/img/glass.png'},
  {name: 'エルコンドルパサー', img: '/img/el.png'},
  {name: 'エアグルーブ', img: '/img/air.png'},
  {name: 'マヤノトップガン', img: '/img/topgun.png'},
  {name: 'スーパークリーク', img: '/img/Creek.png'},
  {name: 'メジロライアン', img: '/img/raian.png'},
  {name: 'アグネスタキオン', img: '/img/takion.png'},
  {name: 'ウイニングチケット', img: '/img/winning.png'},
  {name: 'サクラバクシンオー', img: '/img/sakura.png'},
  {name: 'ハルウララ', img: '/img/urara.png'},
  {name: 'マチカネフクキタル', img: '/img/matikane.png'},
  {name: 'ナイスネイチャ', img: '/img/nice.png'},
  {name: 'キングヘイロー', img: '/img/king.png'},
]

export default UmaDatas